extern int cp(int argc, const char **argv);
extern int mv(int argc, const char **argv);
extern int echo(int argc, const char **argv);
extern int fcd(int argc, const char **argv);
extern int type(int argc, const char **argv);
extern int env(int argc, const char **argv);
extern int external(int argc, const char **argv);
extern int ffree(int argc, const char **argv);
extern int uptime(int argc, const char **argv);
extern void redirect(int oldfd, int newfd);
